### PR TITLE
Added an auto-update plugin registry

### PR DESCRIPTION
**Pull request by johardi**
Hi Fajar,

I've added an auto-update registry in your project to let Protege automatically check your plugin. So when users go to "File > Check for plugins...", they can install the plugin automatically.

A few notes though:
1. Feel free to edit the values in `update-info/protege-5/update.properties` accordingly. The ones that I've made are just an example.
2. Please create a `readme.html` file to describe your plugin. An example: https://raw.githubusercontent.com/protegeproject/cellfie-plugin/master/src/main/resources/readme.html
3. (Optional) I would recommend changing the plugin version to 1.0.0, so people will know the plugin is a production-ready product. Version 0.x usually means a beta version.

Once the `update.properties` is ready, please let me know and I will include your `update.properties` registry in the Protege code base. We would like to promote your plugin to the community basically (:

Let me know if you have any questions!

Best,
Josef

### CODE REVIEW

**Comment by fekaputra** [comment]
Hi Josef, 

Thanks for the PR - I will review it soon, while probably also updating a few components and configuration per your suggestions.

Best, 
Fajar

**Comment by johardi** [comment]
Do you have a readme file to share?

**Comment by fekaputra** [comment]
Hi Josef, 
Sorry for the wait - I updated the version and in the meantime upgrading several dependencies. the html file is now part of the latest release.
Let me know if you need anything else and thanks for the help!

**Comment by johardi** [comment]
Congrats! We have registered your plugin on our autoupdate repository. Protege users can now install **SHACL4Protege** plugin through the "Check for plugins..." menu. 

Screen Shot 2020-03-03 at 1 43 29 PM

**Comment by fekaputra** [comment]
Super! thanks a lot for your help @johardi !

**Pull request merged**
